#include <gtest/gtest.h>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp_action/rclcpp_action.hpp>
#include <std_msgs/msg/float32.hpp>
#include <std_msgs/msg/float64.hpp>
#include <chrono>
#include <thread>
#include <atomic>
#include "../src/WheelMotorNode.cpp"
#include "TestWheelMotor.cpp"
#include "motor_control/EtherCatConfig.hpp"
#include "motor_control/MotorConfig.hpp"
#include "motor_control/action/wheel_fine_control.hpp"
#include <future>

class WheelMotorNodeTest : public ::testing::Test
{
protected:
};

TEST_F(WheelMotorNodeTest, node_creation)
{
   EtherCatConfig ethercat_config; // Assume default constructor is sufficient
   MotorConfig    motor_config;    // Assume default constructor is sufficient
   auto           wheel_motor_node = wheel_motor_control::WheelMotorNode::create(
      "test_wheel",
      rclcpp::NodeOptions(),
      ethercat_config,
      motor_config,
      std::make_unique<TestWheelMotor>());

   ASSERT_NE(wheel_motor_node, nullptr);
   ASSERT_STREQ(wheel_motor_node->get_name(), "test_wheel_wheel_motor_node");
}

TEST_F(WheelMotorNodeTest, velocity_topic_followed)
{
   const float TARGET_VELOCITY = 1.0f; // rad/s

   auto test_node        = std::make_shared<rclcpp::Node>("Test_Node_Velocity_Topic_Followed");
   auto wheel_motor_node = wheel_motor_control::WheelMotorNode::create(
      "test_wheel",
      rclcpp::NodeOptions(),
      EtherCatConfig(),
      MotorConfig(),
      std::make_unique<TestWheelMotor>());

   rclcpp::executors::SingleThreadedExecutor exec;
   exec.add_node(test_node);
   exec.add_node(wheel_motor_node);

   float received_velocity = 0.0f;
   bool  got_response      = false;

   auto velocity_subscriber = test_node->create_subscription<std_msgs::msg::Float32>(
      "test_wheel/current_vel", 10,
      [&received_velocity, &got_response](std_msgs::msg::Float32::SharedPtr float_msg) {
      received_velocity = float_msg->data;
      got_response      = true;
   });

   auto publisher = wheel_motor_node->create_publisher<std_msgs::msg::Float32>("test_wheel/cmd_vel", 10);
   auto message   = std_msgs::msg::Float32();
   message.data = TARGET_VELOCITY;
   publisher->publish(message);

   auto start = std::chrono::steady_clock::now();
   auto end   = start + std::chrono::milliseconds(500);

   while (std::chrono::steady_clock::now() < end)
   {
      exec.spin_some(std::chrono::milliseconds(20));
   }

   ASSERT_TRUE(got_response) << "Never received a response from the node";

   ASSERT_NEAR(received_velocity, TARGET_VELOCITY, 0.01f);
}

// Generated by GPT-5 mini on 2026-01-05
TEST_F(WheelMotorNodeTest, position_supercedes_velocity)
{
   const float TARGET_POSITION    = 2.5f; // rad
   const float INITIAL_VELOCITY   = 0.5f; // rad/s
   const float ZERO_VELOCITY      = 0.0f;
   const float POSITION_TOLERANCE = 0.2f; // rad
   const float GOAL_TIMEOUT       = 5.0f; // seconds

   auto test_node        = std::make_shared<rclcpp::Node>("Test_Node_Pos_Supercedes");
   auto wheel_motor_node = wheel_motor_control::WheelMotorNode::create(
      "test_wheel",
      rclcpp::NodeOptions(),
      EtherCatConfig(),
      MotorConfig(),
      std::make_unique<TestWheelMotor>());

   rclcpp::executors::SingleThreadedExecutor exec;
   exec.add_node(test_node);
   exec.add_node(wheel_motor_node);

   // Subscribe to current position (expecting std_msgs::msg::Float64)
   double            received_position = 0.0;
   std::atomic<bool> got_position{ false };

   // print out the current position
   std::vector<double> recorded_positions;
   auto                position_sub = test_node->create_subscription<std_msgs::msg::Float64>(
      "test_wheel/current_position", 10,
      [&received_position, &got_position, &recorded_positions](std_msgs::msg::Float64::SharedPtr msg) {
      received_position = msg->data;
      got_position      = true;
      recorded_positions.push_back(msg->data);
      // also print each sample immediately (force flush)
      std::cout << "[DEBUG] current_position = " << msg->data << std::endl;
      std::cout.flush();
   });

   // Publisher for velocity commands (std_msgs::msg::Float32)
   auto vel_pub = wheel_motor_node->create_publisher<std_msgs::msg::Float32>("test_wheel/cmd_vel", 10);

   // Allow a short time for connections to form
   auto setup_deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(200);
   while (std::chrono::steady_clock::now() < setup_deadline)
   {
      exec.spin_some(std::chrono::milliseconds(10));
   }

   std::cout << "[DEBUG] Spinning up motor..." << std::endl;

   // Let the wheel spin up by publishing INITIAL_VELOCITY for a short period
   std_msgs::msg::Float32 vel_msg;
   vel_msg.data = INITIAL_VELOCITY;
   auto spin_up_deadline = std::chrono::steady_clock::now() + std::chrono::milliseconds(300);
   while (std::chrono::steady_clock::now() < spin_up_deadline)
   {
      vel_pub->publish(vel_msg);
      exec.spin_some(std::chrono::milliseconds(10));
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
   }

   // Create action client and wait for server
   using WheelFine = motor_control::action::WheelFineControl;
   auto action_client = rclcpp_action::create_client<WheelFine>(test_node, "test_wheel/fine_control");

   auto wait_start    = std::chrono::steady_clock::now();
   auto wait_deadline = wait_start + std::chrono::seconds(2);
   while (!action_client->wait_for_action_server(std::chrono::milliseconds(100)) &&
          std::chrono::steady_clock::now() < wait_deadline)
   {
      exec.spin_some(std::chrono::milliseconds(10));
   }
   ASSERT_TRUE(action_client->wait_for_action_server(std::chrono::milliseconds(0)))
      << "Action server not available for fine_control";

   // Prepare and send goal
   WheelFine::Goal goal_msg;
   // The field name below should match the action definition (commonly 'position' or 'target_position').
   // If your action uses a different name, adjust the assignment accordingly.
   goal_msg.target_position = TARGET_POSITION;

   std::promise<void> result_promise;
   auto               result_future = result_promise.get_future();

   rclcpp_action::Client<WheelFine>::SendGoalOptions options;
   options.result_callback = [&result_promise](const rclcpp_action::ClientGoalHandle<WheelFine>::WrappedResult& /*result*/) {
                                result_promise.set_value();
                             };

   std::cout << "[DEBUG] Sending position goal and 0 velocity target..." << std::endl;
   auto send_goal_future = action_client->async_send_goal(goal_msg, options);

   // Immediately publish zero velocity so it doesn't spin back up after the goal is finished
   std_msgs::msg::Float32 zero_msg;
   zero_msg.data = ZERO_VELOCITY;
   vel_pub->publish(zero_msg);

   // Wait for the action result with a timeout, spinning the executor
   auto action_wait_deadline = std::chrono::steady_clock::now() + std::chrono::duration<double>(GOAL_TIMEOUT);
   while (result_future.wait_for(std::chrono::milliseconds(0)) != std::future_status::ready &&
          std::chrono::steady_clock::now() < action_wait_deadline)
   {
      exec.spin_some(std::chrono::milliseconds(20));
      std::this_thread::sleep_for(std::chrono::milliseconds(5));
   }

   // Ensure we received at least one position message
   ASSERT_TRUE(got_position.load()) << "Never received a position update from the node";

   // validate we reached the target
   EXPECT_NEAR(received_position, TARGET_POSITION, POSITION_TOLERANCE)
      << "Wheel did not reach target position within tolerance";
}


int main(int argc, char **argv)
{
   testing::InitGoogleTest(&argc, argv);
   rclcpp::init(argc, argv);
   int ret = RUN_ALL_TESTS();
   rclcpp::shutdown();
   return ret;
}
