controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    erob_controller:
      type: forward_command_controller/ForwardCommandController

joint_state_broadcaster:
  ros__parameters:
    joints:
      - erob_joint
    map_interface_to_joint_state:
      position: position
      velocity: velocity

erob_controller:
  ros__parameters:
    joints:
      - erob_joint
    interface_name: position  # CiA402 cyclic synchronous position (mode 8)
                               # Change to velocity for CSVelocity (mode 9)
                               # Change to effort for CSTorque (mode 10)